// labTestData.ts
import { Activity, Microscope, TestTube } from "lucide-react";
import { LabTestsType } from "./labTestTypes";

export const labTests: LabTestsType = {
  Hematology: {
    icon: <Activity className="h-5 w-5" />,
    tests: {
      "Complete Blood Count (CBC)": {
        parameters: [
          {
            name: "White Blood Cells (WBC)",
            unit: "cells/cm3",
            normalRange: "4,000-11,000",
            type: "number",
          },
          // {
          //   name:"Diff",
          //   unit:"%",
          //   normalRange:""
          // }
          {
            name: "Red Blood Cells (RBC)",
            unit: "cells/cm3",
            normalRange: "4.5-5.5 million",
            type: "number",
          },
          {
            name: "Hemoglobin (Hgb)",
            unit: "g/dL",
            normalRange: "12-16",
            type: "number",
          },
          {
            name: "Packed Cell Volume (PCV)",
            unit: "%",
            normalRange: "36-46",
            type: "number",
          },
          {
            name: "Neutrophils",
            unit: "%",
            normalRange: "55-70%",
            type: "number",
          },
          {
            name: "Lymphocytes",
            unit: "%",
            normalRange: "25-40%",
            type: "number",
          },
          {
            name: "Monocytes",
            unit: "%",
            normalRange: "2-8%",
            type: "number",
          },
          {
            name: "Eosinophils",
            unit: "%",
            normalRange: "1-6%",
            type: "number",
          },
          {
            name: "Basophils",
            unit: "%",
            normalRange: "0-1%",
            type: "number",
          },
          {
            name: "Platelets",
            unit: "cells/μL",
            normalRange: "150,000-450,000",
            type: "number",
          },
          {
            name: "MCHC",
            unit: "%",
            normalRange: "32-36%",
            type: "number",
          },
          {
            name: "Mean Corpuscular Volume (MCV)",
            unit: "fL",
            normalRange: "80-100",
            type: "number",
          },
        ],
      },
      "Erythrocyte Sedimentation Rate (ESR)": {
        parameters: [
          {
            name: "ESR",
            unit: "mm/hr",
            normalRange: "Men: 0-22, Women: 0-29",
            type: "number",
          },
        ],
      },
      "Bleeding Time": {
        parameters: [
          {
            name: "Bleeding Time",
            unit: "minutes",
            normalRange: "2-7",
            type: "number",
          },
          {
            name: "Clotting Time",
            unit: "minutes",
            normalRange: "3-8",
            type: "number",
          },
        ],
      },
      "Blood Group & Genotype": {
        parameters: [
          {
            name: "Blood",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Genotype",
            unit: "",
            normalRange: "",
            type: "text",
          },
        ],
      },
      Microfilaria: {
        parameters: [
          {
            name: "Microfilaria",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["Seen", "Not seen"],
          },
        ],
      },
    },
  },
  "Clinical Chemistry": {
    icon: <TestTube className="h-5 w-5" />,
    tests: {
      "Liver Function Tests (LFT)": {
        parameters: [
          {
            name: "ALT (SGPT)",
            unit: "U/L",
            normalRange: "7-56",
            type: "number",
          },
          {
            name: "AST (SGOT)",
            unit: "U/L",
            normalRange: "10-40",
            type: "number",
          },
          {
            name: "Alkaline Phosphatase",
            unit: "U/L",
            normalRange: "44-147",
            type: "number",
          },
          {
            name: "Total Bilirubin",
            unit: "mg/dL",
            normalRange: "0.3-1.2",
            type: "number",
          },
          {
            name: "Direct Bilirubin",
            unit: "mg/dL",
            normalRange: "0.1-0.3",
            type: "number",
          },
          {
            name: "Total Protein",
            unit: "g/dL",
            normalRange: "6.0-8.3",
            type: "number",
          },
          {
            name: "Albumin",
            unit: "g/dL",
            normalRange: "3.5-5.0",
            type: "number",
          },
        ],
      },
      "Kidney Function Tests (KFT)": {
        parameters: [
          {
            name: "Blood Urea Nitrogen (BUN)",
            unit: "mg/dL",
            normalRange: "15-50",
            type: "number",
          },
          {
            name: "Creatinine",
            unit: "mg/dL",
            normalRange: "0.7-1.3",
            type: "number",
          },
          {
            name: "Uric Acid",
            unit: "mg/dL",
            normalRange: "3.4-7.0",
            type: "number",
          },
          // {
          //   name: "eGFR",
          //   unit: "mL/min/1.73m²",
          //   normalRange: ">60",
          //   type: "number",
          // },
          {
            name: "Sodium",
            unit: "mEg/l",
            normalRange: "133-146",
            type: "number",
          },
          {
            name: "Pottasium",
            unit: "mEg/l",
            normalRange: "3.5-5",
            type: "number",
          },
          {
            name: "Bicarbonate",
            unit: "mEg/l",
            normalRange: "21-30",
            type: "number",
          },
          {
            name: "Chloride",
            unit: "mEg/l",
            normalRange: "96-106",
            type: "number",
          },
        ],
      },
      "Lipid Profile": {
        parameters: [
          {
            name: "Total Cholesterol",
            unit: "mg/dL",
            normalRange: "150-250",
            type: "number",
          },
          {
            name: "HDL Cholesterol",
            unit: "mg/dL",
            normalRange: ">60",
            type: "number",
          },
          {
            name: "LDL Cholesterol",
            unit: "mg/dL",
            normalRange: "<100",
            type: "number",
          },
          {
            name: "Triglycerides",
            unit: "mg/dL",
            normalRange: "70-170",
            type: "number",
          },
          {
            name: "Total Cholesterol / HDL Cholesterol",
            unit: "",
            normalRange: "",
            type: "number",
          },
        ],
      },
      "Blood Glucose": {
        parameters: [
          {
            name: "Fasting Blood Sugar",
            unit: "mg/dL",
            normalRange: "70-115",
            type: "number",
          },
          {
            name: "Random Blood Sugar",
            unit: "mg/dL",
            normalRange: "75-145",
            type: "number",
          },
          { name: "HbA1c", unit: "%", normalRange: "<5.7", type: "number" },
        ],
      },
    },
  },
  Serology: {
    icon: <Microscope className="h-5 w-5" />,
    tests: {
      "Widal Test": {
        parameters: [
          {
            name: "Salmonella Typhi O",
            unit: "Titre",
            // normalRange: "<1:80",
            type: "text",
          },
          {
            name: "Salmonella Typhi H",
            unit: "Titre",
            // normalRange: "<1:80",
            type: "text",
          },
          {
            name: "Salmonella Paratyphi A O",
            unit: "Titre",
            // normalRange: "<1:80",
            type: "text",
          },
          {
            name: "Salmonella Paratyphi A H",
            unit: "Titre",
            // normalRange: "<1:80",
            type: "text",
          },
          {
            name: "Salmonella Paratyphi B O",
            unit: "Titre",
            // normalRange: "<1:80",
            type: "text",
          },
          {
            name: "Salmonella Paratyphi B H",
            unit: "Titre",
            // normalRange: "<1:80",
            type: "text",
          },
          {
            name: "Salmonella Paratyphi C O",
            unit: "Titre",
            // normalRange: "<1:80",
            type: "text",
          },
          {
            name: "Salmonella Paratyphi C H",
            unit: "Titre",
            // normalRange: "<1:80",
            type: "text",
          },
        ],
      },
      "Screening Panel": {
        parameters: [
          {
            name: "HBsAg",
            unit: "",
            // normalRange: "",
            type: "select",
            options: ["Positive", "Negative"],
          },
          {
            name: "HCV Ab",
            unit: "",
            // normalRange: "",
            type: "select",
            options: ["Positive", "Negative"],
          },
          {
            name: "HAV IgM",
            unit: "",
            // normalRange: "",
            type: "select",
            options: ["Positive", "Negative"],
          },
          {
            name: "VDRL",
            unit: "",
            // normalRange: "",
            type: "select",
            options: ["Positive", "Negative"],
          },
          {
            name: "H-Pylori",
            unit: "",
            // normalRange: "",
            type: "select",
            options: ["Positive", "Negative"],
          },
          {
            name: "TB-Antigen",
            unit: "",
            // normalRange: "",
            type: "select",
            options: ["Positive", "Negative"],
          },
          {
            name: "Pregnancy Test",
            unit: "",
            // normalRange: "",
            type: "select",
            options: ["Positive", "Negative"],
          },
          {
            name: "PSA",
            unit: "",
            // normalRange: "",
            type: "select",
            options: ["Positive", "Negative"],
          },
          {
            name: "HIV 1 & 2",
            unit: "",
            // normalRange: "",
            type: "select",
            options: ["Reactive", "Non-reactive"],
          },
        ],
      },
    },
  },
  Microbiology: {
    icon: <Activity className="h-5 w-5" />,
    tests: {
      "Malaria Parasite": {
        parameters: [
          {
            name: "Malaria Parasite",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Not seen"],
          },
        ],
      },
      "Urine Culture": {
        parameters: [
          {
            name: "Organism Isolated",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Colony Count",
            unit: "CFU/mL",
            normalRange: "",
            type: "text",
          },

          {
            name: "Pus Cells",
            unit: "/hpf",
            normalRange: "",
            type: "number",
          },
          { name: "RBC", unit: "/hpf", normalRange: "", type: "number" },
          {
            name: "Epithelial Cells",
            unit: "/hpf",
            normalRange: "",
            type: "text",
          },
          { name: "Bacteria", unit: "", normalRange: "", type: "text" },
          { name: "T.Vaginalis", unit: "", normalRange: "", type: "text" },
          { name: "Crystals", unit: "", normalRange: "", type: "text" },
          { name: "Cast", unit: "", normalRange: "", type: "text" },

          // {
          //   name: "Sensitivity",
          //   unit: "",
          //   normalRange: "",
          //   type: "textarea",
          // },
          {
            name: "Pencillin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Tetracyclin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Gentymacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Amoxicillin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ampiclox",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Levofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Cefuroxine",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ciprofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Chlorampheicol",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Azithromycin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Cotrimazole",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ceftriaxone",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Erythromycin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Sparfloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Augmetin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Pefloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ceftaxim",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Zinnacef",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Rocephin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
        ],
      },
      "Wound/Swab Culture": {
        parameters: [
          {
            name: "Organism Isolated",
            unit: "",
            normalRange: "No growth",
            type: "text",
          },

          {
            name: "Pus Cells",
            unit: "/hpf",
            normalRange: "0-5",
            type: "number",
          },
          { name: "RBC", unit: "/hpf", normalRange: "0-2", type: "number" },
          {
            name: "Epithelial Cells",
            unit: "/hpf",
            normalRange: "",
            type: "text",
          },
          { name: "Bacteria", unit: "", normalRange: "", type: "text" },
          { name: "T.Vaginalis", unit: "", normalRange: "", type: "text" },
          { name: "Crystals", unit: "", normalRange: "", type: "text" },
          { name: "Cast", unit: "", normalRange: "", type: "text" },

          // {
          //   name: "Sensitivity",
          //   unit: "",
          //   normalRange: "",
          //   type: "textarea",
          // },
          {
            name: "Pencillin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Tetracyclin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Gentymacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Amoxicillin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ampiclox",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Levofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Cefuroxine",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ciprofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Chlorampheicol",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Azithromycin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Cotrimazole",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ceftriaxone",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Erythromycin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Sparfloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Augmetin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Pefloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ceftaxim",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Zinnacef",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Rocephin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
        ],
      },
      "Stool Culture": {
        parameters: [
          {
            name: "Organism Isolated",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Parasites",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Ova/Cysts",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Pus Cells",
            unit: "/hpf",
            normalRange: "",
            type: "number",
          },
          { name: "RBC", unit: "/hpf", normalRange: "", type: "number" },
          {
            name: "Epithelial Cells",
            unit: "/hpf",
            normalRange: "",
            type: "text",
          },
          { name: "Bacteria", unit: "", normalRange: "", type: "text" },
          { name: "T.Vaginalis", unit: "", normalRange: "", type: "text" },
          { name: "Crystals", unit: "", normalRange: "", type: "text" },
          { name: "Cast", unit: "", normalRange: "", type: "text" },

          // {
          //   name: "Sensitivity",
          //   unit: "",
          //   normalRange: "",
          //   type: "textarea",
          // },
          {
            name: "Pencillin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Tetracyclin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Gentymacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Amoxicillin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ampiclox",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Levofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Cefuroxine",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ciprofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Chlorampheicol",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Azithromycin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Cotrimazole",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ceftriaxone",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Erythromycin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Sparfloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Augmetin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Pefloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ceftaxim",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Zinnacef",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Rocephin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
        ],
      },
      "Sputum Culture": {
        parameters: [
          {
            name: "Organism Isolated",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Parasites",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Ova/Cysts",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Pus Cells",
            unit: "/hpf",
            normalRange: "",
            type: "number",
          },
          { name: "RBC", unit: "/hpf", normalRange: "", type: "number" },
          {
            name: "Epithelial Cells",
            unit: "/hpf",
            normalRange: "",
            type: "text",
          },
          { name: "Bacteria", unit: "", normalRange: "", type: "text" },
          { name: "T.Vaginalis", unit: "", normalRange: "", type: "text" },
          { name: "Crystals", unit: "", normalRange: "", type: "text" },
          { name: "Cast", unit: "", normalRange: "", type: "text" },

          // {
          //   name: "Sensitivity",
          //   unit: "",
          //   normalRange: "",
          //   type: "textarea",
          // },
          {
            name: "Pencillin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Tetracyclin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Gentymacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Amoxicillin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ampiclox",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Levofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Cefuroxine",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ciprofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Chlorampheicol",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Azithromycin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Cotrimazole",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ceftriaxone",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Erythromycin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Sparfloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Augmetin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Pefloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ceftaxim",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Zinnacef",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Rocephin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
        ],
      },
      "Seminal Fluid Analysis": {
        parameters: [
          {
            name: "Organism Isolated",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Time of Production",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Time Examined",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Method of Production",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Color",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Volume",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "PH",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Viscosity",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Consistency",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Big Head",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "No Tail",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Epithelia Cells",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Pus Cells",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Counts",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Abnormal Form",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Normal Form",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Fully Active",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Slightly Active",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Dead",
            unit: "",
            normalRange: "",
            type: "text",
          },
          {
            name: "Pencillin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Tetracyclin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Gentymacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Amoxicillin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ampiclox",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Levofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Cefuroxine",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ciprofloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Chlorampheicol",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Azithromycin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Cotrimazole",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ceftriaxone",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Erythromycin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Sparfloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Augmetin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Pefloxacin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Ceftaxim",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Zinnacef",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Rocephin",
            unit: "",
            normalRange: "",
            type: "select",
            options: ["+", "++", "+++", "Resistant"],
          },
          {
            name: "Comment",
            unit: "",
            normalRange: "",
            type: "textarea",
          },
        ],
      },
    },
  },
  Urinalysis: {
    icon: <TestTube className="h-5 w-5" />,
    tests: {
      "Routine Urine Examination": {
        parameters: [
          {
            name: "Color",
            unit: "",
            // normalRange: "Pale yellow",
            type: "text",
          },
          {
            name: "Appearance",
            unit: "",
            // normalRange: "Clear",
            type: "text",
          },
          {
            name: "Specific Gravity",
            unit: "",
            // normalRange: "1.003-1.030",
            type: "number",
          },
          {
            name: "pH",
            unit: "",
            //  normalRange: "5.0-8.0",
            type: "number",
          },
          {
            name: "Bilirubin",
            unit: "",
            // normalRange: "Clear",
            type: "select",
            options: ["Negative", "Trace", "+", "++", "+++"],
          },
          {
            name: "Urobillnogen",
            unit: "",
            // normalRange: "Clear",
            type: "select",
            options: ["Negative", "Trace", "+", "++", "+++"],
          },

          {
            name: "Leucocyte",
            unit: "",
            // normalRange: "Clear",
            type: "select",
            options: ["Negative", "Trace", "+", "++", "+++"],
          },
          {
            name: "Ascorbic acid",
            unit: "",
            // normalRange: "Clear",
            type: "select",
            options: ["Negative", "Trace", "+", "++", "+++"],
          },
          {
            name: "Nitrite",
            unit: "",
            // normalRange: "Clear",
            type: "select",
            options: ["Negative", "Trace", "+", "++", "+++"],
          },
          {
            name: "Protein",
            unit: "",
            // normalRange: "Negative",
            type: "select",
            options: ["Negative", "Trace", "+", "++", "+++"],
          },
          {
            name: "Glucose",
            unit: "",
            // normalRange: "Negative",
            type: "select",
            options: ["Negative", "Trace", "+", "++", "+++"],
          },
          {
            name: "Ketones",
            unit: "",
            // normalRange: "Negative",
            type: "select",
            options: ["Negative", "Trace", "+", "++", "+++"],
          },
          {
            name: "Blood",
            unit: "",
            // normalRange: "Negative",
            type: "select",
            options: ["Negative", "Trace", "+", "++", "+++"],
          },
        ],
      },
    },
  },
};
